### ISSUE TITLE
Using an encrypted key not possible

### ISSUE THREAD

**Issue by Putzeimer** [william89731/node-red-contrib-ssh-v3#13]
If I use a passphrase encrypted key, I get the following error and node-red crashes (=> my docker container stops).
```
[error] Error: Cannot parse privateKey: Encrypted private OpenSSH key detected, but no passphrase given
    at Client.connect (/data/node_modules/ssh2/lib/client.js:261:15)
    at _connectClient (/data/node_modules/node-red-contrib-ssh-v3/ssh.js:56:15)
    at async SshV3._inputCallback (/data/node_modules/node-red-contrib-ssh-v3/ssh.js:136:4)
```
I pasted the passphrase in the password field, but it seems to be ignored when using a key.

**Comment by william89731** [comment]
passphrase will be supported in future releases
